13 ctra model
usdot-fhwa-stol/cooperative-perception-core pull request #19
Opened 2023-01-21 14:58 UTC by reyespinr

# PR Details
## Description

This PR contains the implementation of the Constant Turn Rate and Acceleration model. This model describes the motion of a vehicle or object with a constant yaw rate and acceleration. The CTRA model includes a state vector `CtraState` with six state variables: x and y position, heading angle, velocity, turning rate, and acceleration. The Angle class is implemented into the motion model.

## Related Issue
Missing CTRA model: https://github.com/usdot-fhwa-stol/cooperative-perception-core/issues/13

## Motivation and Context

This motion model is used in the prediction step of the Unscented Kalman filter that will be used for temporal alignment.

## How Has This Been Tested?

Created unit test to validate the model. Results for the unit tests were validated by using Python script and manual calculations.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-01-24 18:58 UTC, MishkaMN reviewed
Test

2023-01-24 19:41 UTC, adamlm requested changes
Minor formatting changes. See line specific comments.

2023-01-24 19:41 UTC, adamlm commented on src/CMakeLists.txt
> +  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
Needs an extra indent. It should look like:
```cmake
target_include_directories(cooperative_perception_coreLibrary
  PUBLIC
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
)
```

2023-01-24 19:41 UTC, adamlm commented on src/CMakeLists.txt
> +  units::units
Needs an extra indent. It should look like:
```cmake
target_link_libraries(cooperative_perception_coreLibrary
  PUBLIC
    Boost::container
    Eigen3::Eigen
    units::units
)
```

2023-01-24 19:41 UTC, adamlm commented on test/CMakeLists.txt
> +  GTest::Main
Needs an extra indent. It should look like:
```cmake
target_link_libraries(test_cooperative_perceptionExecutable
  PRIVATE
    cooperative_perception::cooperative_perception
    GTest::GTest
    GTest::Main
)
```

2023-01-24 19:52 UTC, adamlm approved these changes
Looks good to me.

2023-01-26 17:20 UTC, MishkaMN commented
Looks good to me

2023-01-26 17:20 UTC, MishkaMN approved these changes

2023-01-26 17:35 UTC, merged